# -*- coding: utf-8 -*-
"""Merge Strings Alternately.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Rr6ii6GulpiNufZUoc69J9Y7d7Tp3U-

# 1768. [Merge Strings Alternately](https://leetcode.com/problems/merge-strings-alternately)

#### You are given two strings ```word1``` and ```word2```. Merge the strings by adding letters in alternating order, starting with ```word1```. If a string is longer than the other, append the additional letters onto the end of the merged string.
"""

word1, word2 = 'abcde', 'pqrtubgf'
print(word1)
print(word2)

A, B = len(word1), len(word2)
a, b = 0, 0
s = []
word = 1

while a < A and b < B:
  if word == 1:
    s.append(word1[a])
    a += 1
    word = 2
  else:
    s.append(word2[b])
    b += 1
    word = 1
while a < A:
  s.append(word1[a])
  a +=1
while b < B:
  s.append(word2[b])
  b += 1

print(''.join(s))

